-- +goose Up
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE likes;
TRUNCATE TABLE comments;
TRUNCATE TABLE article_tags;
TRUNCATE TABLE articles;
TRUNCATE TABLE tags;
TRUNCATE TABLE categories;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;